sudo: false
language: node_js
node_js:
  - "8.10"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn install
  - npm rebuild node-sass

script:
  - yarn lint-all
  - yarn test:coverage
  - codecov
  - yarn build

notifications:
  email: false
