sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - npm run build
  - npm run build-prod
  - npm test
 
after_success:
  - npm run lint-all