sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn install
  - npm rebuild node-sass

script:
  - npm run lint-all
  - npm test
  - npm run build-prod

notifications:
  email: false